services:
  - type: web
    name: mineshish-website
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MINECRAFT_PLUGIN_URL
        value: http://YOUR_MINECRAFT_SERVER_IP:8081/stats
      - key: SECRET_TOKEN
        generateValue: true
      - key: NODE_VERSION
        value: 20.11.1

